In [1]:
from sklearn import datasets

iris = datasets.load_iris()
X = iris.data
y = iris.target
X.shape, y.shape

((150, 4), (150,))

In [2]:
import numpy as np
print("Les attributs dans le jeu de données Iris :")
iris.feature_names
np.unique(y)

Les attributs dans le jeu de données Iris :


array([0, 1, 2])

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=90
)
X_train.shape

(105, 4)

In [4]:
from sklearn.svm import SVC

svm_model = SVC(C=0.1, gamma="auto", kernel="linear")
svm_model.fit(X_train, y_train)

SVC(C=0.1, gamma='auto', kernel='linear')

In [16]:
y_pred = svm_model.predict(X_test)

In [17]:
y_test, y_pred

(array([1, 0, 0, 2, 2, 0, 1, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2,
        2, 0, 1, 1, 2, 2, 2, 0, 0, 0, 2, 2, 0, 2, 2, 2, 1, 0, 2, 1, 0, 0,
        0]),
 array([1, 0, 0, 2, 2, 0, 1, 2, 0, 2, 2, 0, 2, 2, 0, 2, 1, 0, 1, 1, 1, 2,
        2, 0, 1, 1, 2, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 0,
        0]))

In [7]:
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(y_test, y_pred)
print("Matrice de confusion :")
print(conf_matrix)

Matrice de confusion :
[[16  0  0]
 [ 0  8  1]
 [ 0  2 18]]


In [8]:
from sklearn.model_selection import GridSearchCV

param_grid = {"C": [0.001, 0.01, 0.1, 1, 10], "gamma": ["scale", "auto"]}
grid_search = GridSearchCV(SVC(kernel="linear"), param_grid, cv=5)
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(kernel='linear'),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10],
                         'gamma': ['scale', 'auto']})

In [9]:
print("Les meilleurs paramètres trouvés par GridSearchCV :")
print(grid_search.best_params_)

Les meilleurs paramètres trouvés par GridSearchCV :
{'C': 1, 'gamma': 'scale'}


In [10]:
# 1. Classifier=SVC(c=0.006, kernel='rbf', gamma='scale')
classifier_rbf = SVC(C=0.006, kernel="rbf", gamma="scale")
classifier_rbf.fit(X_train, y_train)
y_pred_rbf = classifier_rbf.predict(X_test)

In [11]:
# Afficher la matrice de confusion pour le kernel 'rbf'
conf_matrix_rbf = confusion_matrix(y_test, y_pred_rbf)
print("Matrice de confusion pour le kernel 'rbf' :")
print(conf_matrix_rbf)

Matrice de confusion pour le kernel 'rbf' :
[[ 0 16  0]
 [ 0  9  0]
 [ 0 20  0]]


In [12]:
# 2. Classifier=SVC(c=1, kernel='poly', gamma='auto', degree=7)
classifier_poly = SVC(C=1, kernel="poly", gamma="auto", degree=7)
classifier_poly.fit(X_train, y_train)
y_pred_poly = classifier_poly.predict(X_test)

In [13]:
# Afficher la matrice de confusion pour le kernel 'poly'
conf_matrix_poly = confusion_matrix(y_test, y_pred_poly)
print("Matrice de confusion pour le kernel 'poly' :")
print(conf_matrix_poly)

Matrice de confusion pour le kernel 'poly' :
[[16  0  0]
 [ 0  8  1]
 [ 0  1 19]]


In [14]:
# Partie 3 :

# Utiliser le jeu de données breast_cancer de Scikit-Learn
from sklearn.datasets import load_breast_cancer

cancer_data = load_breast_cancer()
X_cancer = cancer_data.data
y_cancer = cancer_data.target

# Diviser les données en jeu d'entrainement et jeu de test
X_train_cancer, X_test_cancer, y_train_cancer, y_test_cancer = train_test_split(
    X_cancer, y_cancer, test_size=0.3, random_state=42
)

# Créer une SVM pour différencier tumeurs malignes des tumeurs bénignes
svm_cancer = SVC(kernel="linear")
svm_cancer.fit(X_train_cancer, y_train_cancer)

# Prédire le jeu de données test
y_pred_cancer = svm_cancer.predict(X_test_cancer)

# Afficher la matrice de confusion pour la classification des tumeurs malignes et bénignes
conf_matrix_cancer = confusion_matrix(y_test_cancer, y_pred_cancer)
print("Matrice de confusion pour la classification des tumeurs malignes et bénignes :")
print(conf_matrix_cancer)

Matrice de confusion pour la classification des tumeurs malignes et bénignes :
[[ 59   4]
 [  2 106]]
